/* Generated By:JJTree: Do not edit this line. ASTEqualityCompute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package runtime.parser;

public class ASTEqualityCompute extends Compute {
  public ASTEqualityCompute(int id) {
    super(id);
  }

  public ASTEqualityCompute(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a811bfa231103b607c076a3be0a2c376 (do not edit this line) */
