/* Generated By:JJTree: Do not edit this line. ASTEqualityCompute.java */

package runtime.parser;

public class ASTEqualityCompute extends Compute {
  public ASTEqualityCompute(int id) {
    super(id);
  }

  public ASTEqualityCompute(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
