/* Generated By:JJTree: Do not edit this line. ASTLogicalCompute.java */

package runtime.parser;

public class ASTLogicalCompute extends Compute {
  public ASTLogicalCompute(int id) {
    super(id);
  }

  public ASTLogicalCompute(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
