/* Generated By:JJTree: Do not edit this line. ASTAssignTo.java */

package runtime.parser;

public class ASTAssignTo extends SimpleNode {
  public ASTAssignTo(int id) {
    super(id);
  }

  public ASTAssignTo(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
