/* Generated By:JJTree: Do not edit this line. ASTAlias.java */

package runtime.parser;

public class ASTAlias extends SimpleNode {
  public ASTAlias(int id) {
    super(id);
  }

  public ASTAlias(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
