/* Generated By:JJTree: Do not edit this line. ASTAliasType.java */

package runtime.parser;

public class ASTAliasType extends SimpleNode {
  public ASTAliasType(int id) {
    super(id);
  }

  public ASTAliasType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
