/* Generated By:JJTree: Do not edit this line. ASTCondType.java */

package runtime.parser;

public class ASTCondType extends SimpleNode {
  public ASTCondType(int id) {
    super(id);
  }

  public ASTCondType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
