/* Generated By:JJTree: Do not edit this line. ASTConditionMsg.java */

package runtime.parser;

public class ASTConditionMsg extends SimpleNode {
  public ASTConditionMsg(int id) {
    super(id);
  }

  public ASTConditionMsg(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
