/* Generated By:JJTree: Do not edit this line. ASTDivOperator.java */

package runtime.parser;

public class ASTDivOperator extends SimpleNode {
  public ASTDivOperator(int id) {
    super(id);
  }

  public ASTDivOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
