/* Generated By:JJTree: Do not edit this line. ASTEqualityOperator.java */

package runtime.parser;

public class ASTEqualityOperator extends SimpleNode {
  public ASTEqualityOperator(int id) {
    super(id);
  }

  public ASTEqualityOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
