/* Generated By:JJTree: Do not edit this line. ASTExptn.java */

package runtime.parser;

public class ASTExptn extends SimpleNode {
  public ASTExptn(int id) {
    super(id);
  }

  public ASTExptn(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
