/* Generated By:JJTree: Do not edit this line. ASTElseActions.java */

package runtime.parser;

public class ASTElseActions extends SimpleNode {
  public ASTElseActions(int id) {
    super(id);
  }

  public ASTElseActions(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
