/* Generated By:JJTree: Do not edit this line. ASTExptnType.java */

package runtime.parser;

public class ASTExptnType extends SimpleNode {
  public ASTExptnType(int id) {
    super(id);
  }

  public ASTExptnType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
