/* Generated By:JJTree: Do not edit this line. ASTFunctionRefArg.java */

package runtime.parser;

public class ASTFunctionRefArg extends SimpleNode {
  public ASTFunctionRefArg(int id) {
    super(id);
  }

  public ASTFunctionRefArg(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
