/* Generated By:JJTree: Do not edit this line. ASTFilename.java */

package runtime.parser;

public class ASTFilename extends SimpleNode {
  public ASTFilename(int id) {
    super(id);
  }

  public ASTFilename(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
