/* Generated By:JJTree: Do not edit this line. ASTFunctionRef.java */

package runtime.parser;

public class ASTFunctionRef extends SimpleNode {
  public ASTFunctionRef(int id) {
    super(id);
  }

  public ASTFunctionRef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
