/* Generated By:JJTree: Do not edit this line. ASTFunctionDefArgList.java */

package runtime.parser;

public class ASTFunctionDefArgList extends SimpleNode {
  public ASTFunctionDefArgList(int id) {
    super(id);
  }

  public ASTFunctionDefArgList(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
