/* Generated By:JJTree: Do not edit this line. ASTFunctionRefArgList.java */

package runtime.parser;

public class ASTFunctionRefArgList extends SimpleNode {
  public ASTFunctionRefArgList(int id) {
    super(id);
  }

  public ASTFunctionRefArgList(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
