/* Generated By:JJTree: Do not edit this line. ASTFunctionDefArg.java */

package runtime.parser;

public class ASTFunctionDefArg extends SimpleNode {
  public ASTFunctionDefArg(int id) {
    super(id);
  }

  public ASTFunctionDefArg(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
