/* Generated By:JJTree: Do not edit this line. ASTGuidelineDef.java */

package runtime.parser;

public class ASTGuidelineDef extends SimpleNode {
  public ASTGuidelineDef(int id) {
    super(id);
  }

  public ASTGuidelineDef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
