/* Generated By:JJTree: Do not edit this line. ASTImport.java */

package runtime.parser;

public class ASTImport extends SimpleNode {
  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
