/* Generated By:JJTree: Do not edit this line. ASTIfActions.java */

package runtime.parser;

public class ASTIfActions extends SimpleNode {
  public ASTIfActions(int id) {
    super(id);
  }

  public ASTIfActions(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
