/* Generated By:JJTree: Do not edit this line. ASTInclude.java */

package runtime.parser;

public class ASTInclude extends SimpleNode {
  public ASTInclude(int id) {
    super(id);
  }

  public ASTInclude(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
