/* Generated By:JJTree: Do not edit this line. ASTImportType.java */

package runtime.parser;

public class ASTImportType extends SimpleNode {
  public ASTImportType(int id) {
    super(id);
  }

  public ASTImportType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
