/* Generated By:JJTree: Do not edit this line. ASTLookupDef.java */

package runtime.parser;

public class ASTLookupDef extends SimpleNode {
  public ASTLookupDef(int id) {
    super(id);
  }

  public ASTLookupDef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
