/* Generated By:JJTree: Do not edit this line. ASTMessageType.java */

package runtime.parser;

public class ASTMessageType extends SimpleNode {
  public ASTMessageType(int id) {
    super(id);
  }

  public ASTMessageType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
