/* Generated By:JJTree: Do not edit this line. ASTMathConstant.java */

package runtime.parser;

public class ASTMathConstant extends SimpleNode {
  public ASTMathConstant(int id) {
    super(id);
  }

  public ASTMathConstant(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
