/* Generated By:JJTree: Do not edit this line. ASTMessage.java */

package runtime.parser;

public class ASTMessage extends SimpleNode {
  public ASTMessage(int id) {
    super(id);
  }

  public ASTMessage(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
