/* Generated By:JJTree: Do not edit this line. ASTMathExpression.java */

package runtime.parser;

public class ASTMathExpression extends SimpleNode {
  public ASTMathExpression(int id) {
    super(id);
  }

  public ASTMathExpression(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
