/* Generated By:JJTree: Do not edit this line. ASTMultOperator.java */

package runtime.parser;

public class ASTMultOperator extends SimpleNode {
  public ASTMultOperator(int id) {
    super(id);
  }

  public ASTMultOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
