/* Generated By:JJTree: Do not edit this line. ASTMinusOperator.java */

package runtime.parser;

public class ASTMinusOperator extends SimpleNode {
  public ASTMinusOperator(int id) {
    super(id);
  }

  public ASTMinusOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
