/* Generated By:JJTree: Do not edit this line. ASTOrOperator.java */

package runtime.parser;

public class ASTOrOperator extends SimpleNode {
  public ASTOrOperator(int id) {
    super(id);
  }

  public ASTOrOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
