/* Generated By:JJTree: Do not edit this line. ASTPpmVarType.java */

package runtime.parser;

public class ASTPpmVarType extends SimpleNode {
  public ASTPpmVarType(int id) {
    super(id);
  }

  public ASTPpmVarType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
