/* Generated By:JJTree: Do not edit this line. ASTRulesetRef.java */

package runtime.parser;

public class ASTRulesetRef extends SimpleNode {
  public ASTRulesetRef(int id) {
    super(id);
  }

  public ASTRulesetRef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
