/* Generated By:JJTree: Do not edit this line. ASTRuleDef.java */

package runtime.parser;

public class ASTRuleDef extends SimpleNode {
  public ASTRuleDef(int id) {
    super(id);
  }

  public ASTRuleDef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
