/* Generated By:JJTree: Do not edit this line. ASTRuleRef.java */

package runtime.parser;

public class ASTRuleRef extends SimpleNode {
  public ASTRuleRef(int id) {
    super(id);
  }

  public ASTRuleRef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
