/* Generated By:JJTree: Do not edit this line. ASTRulesetDef.java */

package runtime.parser;

public class ASTRulesetDef extends SimpleNode {
  public ASTRulesetDef(int id) {
    super(id);
  }

  public ASTRulesetDef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
