/* Generated By:JJTree: Do not edit this line. ASTRaiseToOperator.java */

package runtime.parser;

public class ASTRaiseToOperator extends SimpleNode {
  public ASTRaiseToOperator(int id) {
    super(id);
  }

  public ASTRaiseToOperator(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
