/* Generated By:JJTree: Do not edit this line. ASTStr.java */

package runtime.parser;

public class ASTStr extends SimpleNode {
  public ASTStr(int id) {
    super(id);
  }

  public ASTStr(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
