/* Generated By:JJTree: Do not edit this line. ASTVarCast.java */

package runtime.parser;

public class ASTVarCast extends SimpleNode {
  public ASTVarCast(int id) {
    super(id);
  }

  public ASTVarCast(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
