/* Generated By:JJTree: Do not edit this line. ASTVarDef.java */

package runtime.parser;

public class ASTVarDef extends SimpleNode {
  public ASTVarDef(int id) {
    super(id);
  }

  public ASTVarDef(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
