/* Generated By:JJTree: Do not edit this line. ASTVariableType.java */

package runtime.parser;

public class ASTVariableType extends SimpleNode {
  public ASTVariableType(int id) {
    super(id);
  }

  public ASTVariableType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
