/* Generated By:JJTree: Do not edit this line. ASTVarType.java */

package runtime.parser;

public class ASTVarType extends SimpleNode {
  public ASTVarType(int id) {
    super(id);
  }

  public ASTVarType(GdlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GdlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
