/* Generated By:JJTree: Do not edit this line. R:\sandbox\net.bd.gdlc\src\runtime\parser\GdlParserVisitor.java */

package runtime.parser;

public interface GdlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCompilationUnit node, Object data);
  public Object visit(ASTVarDef node, Object data);
  public Object visit(ASTAlias node, Object data);
  public Object visit(ASTImport node, Object data);
  public Object visit(ASTInclude node, Object data);
  public Object visit(ASTGuidelineDef node, Object data);
  public Object visit(ASTInsertPricing node, Object data);
  public Object visit(ASTFunctionRef node, Object data);
  public Object visit(ASTFunctionRefArgList node, Object data);
  public Object visit(ASTFunctionRefArg node, Object data);
  public Object visit(ASTFunctionDef node, Object data);
  public Object visit(ASTFunctionDefArgList node, Object data);
  public Object visit(ASTFunctionDefArg node, Object data);
  public Object visit(ASTCodeBlock node, Object data);
  public Object visit(ASTRulesetDef node, Object data);
  public Object visit(ASTRulesetRef node, Object data);
  public Object visit(ASTRuleDef node, Object data);
  public Object visit(ASTRuleRef node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTLogicalCompute node, Object data);
  public Object visit(ASTEqualityCompute node, Object data);
  public Object visit(ASTLogicalOperator node, Object data);
  public Object visit(ASTEqualityOperator node, Object data);
  public Object visit(ASTBrace node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTMathExpression node, Object data);
  public Object visit(ASTMathCompute node, Object data);
  public Object visit(ASTPlusOperator node, Object data);
  public Object visit(ASTMinusOperator node, Object data);
  public Object visit(ASTMultOperator node, Object data);
  public Object visit(ASTDivOperator node, Object data);
  public Object visit(ASTRaiseToOperator node, Object data);
  public Object visit(ASTMathConstant node, Object data);
  public Object visit(ASTIfActions node, Object data);
  public Object visit(ASTElseActions node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTAssignTo node, Object data);
  public Object visit(ASTAssignValue node, Object data);
  public Object visit(ASTLookupDef node, Object data);
  public Object visit(ASTMessage node, Object data);
  public Object visit(ASTExptn node, Object data);
  public Object visit(ASTExptnType node, Object data);
  public Object visit(ASTMessageType node, Object data);
  public Object visit(ASTConditionMsg node, Object data);
  public Object visit(ASTCondType node, Object data);
  public Object visit(ASTPriorTo node, Object data);
  public Object visit(ASTVarRef node, Object data);
  public Object visit(ASTVarCast node, Object data);
  public Object visit(ASTVariableType node, Object data);
  public Object visit(ASTAndOperator node, Object data);
  public Object visit(ASTOrOperator node, Object data);
}
