/* Generated By:JJTree&JavaCC: Do not edit this line. GdlParserConstants.java */
package runtime.parser;

public interface GdlParserConstants {

  int EOF = 0;
  int ALIAS = 7;
  int INCLUDE = 8;
  int IMPORT = 9;
  int DPM = 10;
  int DSM = 11;
  int PPM = 12;
  int DECISION = 13;
  int BOOLEAN = 14;
  int DATE = 15;
  int MONEY = 16;
  int NUMERIC = 17;
  int PERCENTAGE = 18;
  int TEXT = 19;
  int APPLICATION = 20;
  int CREDIT = 21;
  int PRODUCT = 22;
  int GUIDELINE = 23;
  int RULESET = 24;
  int RULE = 25;
  int MESSAGE = 26;
  int IF = 27;
  int THEN = 28;
  int ELSE = 29;
  int END = 30;
  int TRUE = 31;
  int FALSE = 32;
  int CONTINUE = 33;
  int MSG_EXC = 34;
  int MSG_EXC_ASSETS = 35;
  int MSG_FINDINGS = 36;
  int MSG_OBSERVATION = 37;
  int MSG_CREDIT = 38;
  int NUMERIC_CONSTANT = 39;
  int INTEGER_LITERAL = 40;
  int DECIMAL_LITERAL = 41;
  int HEX_LITERAL = 42;
  int OCTAL_LITERAL = 43;
  int FLOATING_POINT_LITERAL = 44;
  int EXPONENT = 45;
  int CHARACTER_LITERAL = 46;
  int STRING_LITERAL = 47;
  int FILENAME_LITERAL = 48;
  int LPAREN = 49;
  int RPAREN = 50;
  int LBRACE = 51;
  int RBRACE = 52;
  int LBRACKET = 53;
  int RBRACKET = 54;
  int SEMICOLON = 55;
  int COMMA = 56;
  int DOT = 57;
  int PL = 58;
  int ASSIGN = 59;
  int QUOTE = 60;
  int DQUOTE = 61;
  int PLUS = 62;
  int MINUS = 63;
  int MULT = 64;
  int DIV = 65;
  int RAISETO = 66;
  int EQU = 67;
  int NEQ1 = 68;
  int NEQ2 = 69;
  int LT = 70;
  int GT = 71;
  int LEQ = 72;
  int GEQ = 73;
  int AND1 = 74;
  int AND2 = 75;
  int OR1 = 76;
  int OR2 = 77;
  int IDENTIFIER = 78;
  int LETTER = 79;
  int DIGIT = 80;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"alias\"",
    "\"include\"",
    "\"import\"",
    "\"dpm\"",
    "\"dsm\"",
    "\"ppm\"",
    "\"decision\"",
    "\"boolean\"",
    "\"date\"",
    "\"money\"",
    "\"numeric\"",
    "\"percentage\"",
    "\"text\"",
    "\"app\"",
    "\"crd\"",
    "\"prd\"",
    "\"guideline\"",
    "\"ruleset\"",
    "\"rule\"",
    "\"message\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"end\"",
    "<TRUE>",
    "<FALSE>",
    "\"continue\"",
    "\"exception\"",
    "\"assets\"",
    "\"findings\"",
    "\"observation\"",
    "\"credit\"",
    "<NUMERIC_CONSTANT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<FILENAME_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"PL\"",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"and\"",
    "\"||\"",
    "\"or\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
