/* Generated By:JJTree: Do not edit this line. R:\sandbox\net.bd.gdlc\src\runtime\parser\GdlParserTreeConstants.java */

package runtime.parser;

public interface GdlParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDEF = 1;
  public int JJTVOID = 2;
  public int JJTALIAS = 3;
  public int JJTIMPORT = 4;
  public int JJTINCLUDE = 5;
  public int JJTGUIDELINEDEF = 6;
  public int JJTINSERTPRICING = 7;
  public int JJTFUNCTIONREF = 8;
  public int JJTFUNCTIONREFARGLIST = 9;
  public int JJTFUNCTIONREFARG = 10;
  public int JJTFUNCTIONDEF = 11;
  public int JJTFUNCTIONDEFARGLIST = 12;
  public int JJTFUNCTIONDEFARG = 13;
  public int JJTCODEBLOCK = 14;
  public int JJTRULESETDEF = 15;
  public int JJTRULESETREF = 16;
  public int JJTRULEDEF = 17;
  public int JJTRULEREF = 18;
  public int JJTCONDITION = 19;
  public int JJTEXPRESSION = 20;
  public int JJTLOGICALCOMPUTE = 21;
  public int JJTEQUALITYCOMPUTE = 22;
  public int JJTLOGICALOPERATOR = 23;
  public int JJTEQUALITYOPERATOR = 24;
  public int JJTBRACE = 25;
  public int JJTCONSTANT = 26;
  public int JJTMATHEXPRESSION = 27;
  public int JJTMATHCOMPUTE = 28;
  public int JJTPLUSOPERATOR = 29;
  public int JJTMINUSOPERATOR = 30;
  public int JJTMULTOPERATOR = 31;
  public int JJTDIVOPERATOR = 32;
  public int JJTRAISETOOPERATOR = 33;
  public int JJTMATHCONSTANT = 34;
  public int JJTIFACTIONS = 35;
  public int JJTELSEACTIONS = 36;
  public int JJTASSIGN = 37;
  public int JJTASSIGNTO = 38;
  public int JJTASSIGNVALUE = 39;
  public int JJTLOOKUPDEF = 40;
  public int JJTMESSAGE = 41;
  public int JJTEXPTN = 42;
  public int JJTEXPTNTYPE = 43;
  public int JJTMESSAGETYPE = 44;
  public int JJTCONDITIONMSG = 45;
  public int JJTCONDTYPE = 46;
  public int JJTPRIORTO = 47;
  public int JJTVARREF = 48;
  public int JJTVARCAST = 49;
  public int JJTVARIABLETYPE = 50;
  public int JJTANDOPERATOR = 51;
  public int JJTOROPERATOR = 52;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDef",
    "void",
    "Alias",
    "Import",
    "Include",
    "GuidelineDef",
    "InsertPricing",
    "FunctionRef",
    "FunctionRefArgList",
    "FunctionRefArg",
    "FunctionDef",
    "FunctionDefArgList",
    "FunctionDefArg",
    "CodeBlock",
    "RulesetDef",
    "RulesetRef",
    "RuleDef",
    "RuleRef",
    "Condition",
    "Expression",
    "LogicalCompute",
    "EqualityCompute",
    "LogicalOperator",
    "EqualityOperator",
    "Brace",
    "Constant",
    "MathExpression",
    "MathCompute",
    "PlusOperator",
    "MinusOperator",
    "MultOperator",
    "DivOperator",
    "RaiseToOperator",
    "MathConstant",
    "IfActions",
    "ElseActions",
    "Assign",
    "AssignTo",
    "AssignValue",
    "LookupDef",
    "Message",
    "Exptn",
    "ExptnType",
    "MessageType",
    "ConditionMsg",
    "CondType",
    "PriorTo",
    "VarRef",
    "VarCast",
    "VariableType",
    "AndOperator",
    "OrOperator",
  };
}
