/* Generated By:JJTree: Do not edit this line. R:\sandbox\net.bd.gdlc\src\runtime\parser\GdlParserTreeConstants.java */

package runtime.parser;

public interface GdlParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDEF = 1;
  public int JJTVOID = 2;
  public int JJTALIAS = 3;
  public int JJTALIASTYPE = 4;
  public int JJTALIASOF = 5;
  public int JJTIMPORT = 6;
  public int JJTINCLUDE = 7;
  public int JJTGUIDELINEDEF = 8;
  public int JJTRULESETDEF = 9;
  public int JJTRULESETREF = 10;
  public int JJTRULEDEF = 11;
  public int JJTRULEREF = 12;
  public int JJTCONDITION = 13;
  public int JJTEXPRESSION = 14;
  public int JJTLOGICALCOMPUTE = 15;
  public int JJTLOGICALOPERATOR = 16;
  public int JJTEQUALITYCOMPUTE = 17;
  public int JJTEQUALITYOPERATOR = 18;
  public int JJTBRACE = 19;
  public int JJTCONSTANT = 20;
  public int JJTMATHEXPRESSION = 21;
  public int JJTMATHCOMPUTE = 22;
  public int JJTPLUSOPERATOR = 23;
  public int JJTMINUSOPERATOR = 24;
  public int JJTMULTOPERATOR = 25;
  public int JJTDIVOPERATOR = 26;
  public int JJTRAISETOOPERATOR = 27;
  public int JJTMATHCONSTANT = 28;
  public int JJTIFACTIONS = 29;
  public int JJTELSEACTIONS = 30;
  public int JJTASSIGN = 31;
  public int JJTASSIGNTO = 32;
  public int JJTASSIGNVALUE = 33;
  public int JJTMESSAGE = 34;
  public int JJTEXPTN = 35;
  public int JJTEXPTNTYPE = 36;
  public int JJTMESSAGETYPE = 37;
  public int JJTVARREF = 38;
  public int JJTVARCAST = 39;
  public int JJTVARIABLETYPE = 40;
  public int JJTANDOPERATOR = 41;
  public int JJTOROPERATOR = 42;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDef",
    "void",
    "Alias",
    "AliasType",
    "AliasOf",
    "Import",
    "Include",
    "GuidelineDef",
    "RulesetDef",
    "RulesetRef",
    "RuleDef",
    "RuleRef",
    "Condition",
    "Expression",
    "LogicalCompute",
    "LogicalOperator",
    "EqualityCompute",
    "EqualityOperator",
    "Brace",
    "Constant",
    "MathExpression",
    "MathCompute",
    "PlusOperator",
    "MinusOperator",
    "MultOperator",
    "DivOperator",
    "RaiseToOperator",
    "MathConstant",
    "IfActions",
    "ElseActions",
    "Assign",
    "AssignTo",
    "AssignValue",
    "Message",
    "Exptn",
    "ExptnType",
    "MessageType",
    "VarRef",
    "VarCast",
    "VariableType",
    "AndOperator",
    "OrOperator",
  };
}
