/* Generated By:JJTree: Do not edit this line. R:\net.bd.gdlc\src\runtime\parser\GdlParserTreeConstants.java */

package runtime.parser;

public interface GdlParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDEF = 1;
  public int JJTVARTYPE = 2;
  public int JJTPPMVARTYPE = 3;
  public int JJTALIAS = 4;
  public int JJTALIASTYPE = 5;
  public int JJTALIASOF = 6;
  public int JJTVOID = 7;
  public int JJTIMPORT = 8;
  public int JJTFILENAME = 9;
  public int JJTIMPORTTYPE = 10;
  public int JJTINCLUDE = 11;
  public int JJTGUIDELINEDEF = 12;
  public int JJTSTR = 13;
  public int JJTNAME = 14;
  public int JJTRULESETDEF = 15;
  public int JJTEXECUTETYPE = 16;
  public int JJTRULESETREF = 17;
  public int JJTRULEDEF = 18;
  public int JJTRULEREF = 19;
  public int JJTCONDITION = 20;
  public int JJTEXPRESSION = 21;
  public int JJTLOGICALCOMPUTE = 22;
  public int JJTLOGICALOPERATOR = 23;
  public int JJTEQUALITYCOMPUTE = 24;
  public int JJTEQUALITYOPERATOR = 25;
  public int JJTBRACE = 26;
  public int JJTCONSTANT = 27;
  public int JJTMATHEXPRESSION = 28;
  public int JJTMATHCOMPUTE = 29;
  public int JJTPLUSOPERATOR = 30;
  public int JJTMINUSOPERATOR = 31;
  public int JJTMULTOPERATOR = 32;
  public int JJTDIVOPERATOR = 33;
  public int JJTRAISETOOPERATOR = 34;
  public int JJTMATHCONSTANT = 35;
  public int JJTIFACTIONS = 36;
  public int JJTELSEACTIONS = 37;
  public int JJTASSIGN = 38;
  public int JJTASSIGNTO = 39;
  public int JJTASSIGNVALUE = 40;
  public int JJTMESSAGE = 41;
  public int JJTEXPTN = 42;
  public int JJTEXPTNTYPE = 43;
  public int JJTMESSAGETYPE = 44;
  public int JJTVARIABLE = 45;
  public int JJTVARCAST = 46;
  public int JJTVARIABLETYPE = 47;
  public int JJTANDOPERATOR = 48;
  public int JJTOROPERATOR = 49;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDef",
    "VarType",
    "PpmVarType",
    "Alias",
    "AliasType",
    "AliasOf",
    "void",
    "Import",
    "Filename",
    "ImportType",
    "Include",
    "GuidelineDef",
    "Str",
    "Name",
    "RulesetDef",
    "ExecuteType",
    "RulesetRef",
    "RuleDef",
    "RuleRef",
    "Condition",
    "Expression",
    "LogicalCompute",
    "LogicalOperator",
    "EqualityCompute",
    "EqualityOperator",
    "Brace",
    "Constant",
    "MathExpression",
    "MathCompute",
    "PlusOperator",
    "MinusOperator",
    "MultOperator",
    "DivOperator",
    "RaiseToOperator",
    "MathConstant",
    "IfActions",
    "ElseActions",
    "Assign",
    "AssignTo",
    "AssignValue",
    "Message",
    "Exptn",
    "ExptnType",
    "MessageType",
    "Variable",
    "VarCast",
    "VariableType",
    "AndOperator",
    "OrOperator",
  };
}
