/* Generated By:JJTree&JavaCC: Do not edit this line. GdlParser.java */
package runtime.parser;

import runtime.main.Log;
import runtime.parser.DumpVisitor;

public class GdlParser/*@bgen(jjtree)*/implements GdlParserTreeConstants, GdlParserConstants {/*@bgen(jjtree)*/
  protected JJTGdlParserState jjtree = new JJTGdlParserState();
  public static void main(String args[]) {
    GdlParser parser;
    if (args.length == 0) {
      Log.status("Guideline Parser :  Reading from standard input . . .");
      parser = new GdlParser(System.in);
    } else if (args.length == 1) {
      Log.status("Guideline Parser :  Reading from file " + args[0] + " . . .");
      try {
        parser = new GdlParser(new java.io.FileInputStream(args[0]));
      } catch (java.io.FileNotFoundException e) {
        Log.error("Guideline Parser :  File " + args[0] + " not found.");
        return;
      }
    } else {
      System.out.println("Guideline Parser :  Usage is one of:");
      System.out.println("         java GdlParser < inputfile");
      System.out.println("OR");
      System.out.println("         java GdlParser inputfile");
      return;
    }
    try {
      ASTCompilationUnit cu = parser.CompilationUnit();
      Log.status("Guideline Parser :  Guideline parsed successfully.");
        dump(cu);
    } catch (ParseException e) {
      Log.error("Guideline Parser :  Encountered errors during parse.");
      Log.error(e.toString());
    }
  }

  public void dump() {
        ((SimpleNode)jjtree.rootNode()).dump(">");

  }

  public static void dump(ASTCompilationUnit cu) {
        DumpVisitor v=new DumpVisitor();

        System.out.print(cu.jjtAccept(v,null));
  //        ((SimpleNode)jjtree.rootNode()).dump(">");

    }

/* CompilationUnit */
  final public ASTCompilationUnit CompilationUnit() throws ParseException {
 /*@bgen(jjtree) CompilationUnit */
  ASTCompilationUnit jjtn000 = new ASTCompilationUnit(JJTCOMPILATIONUNIT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ALIAS:
        case INCLUDE:
        case IMPORT:
        case DPM:
        case PPM:
        case RULESET:
        case RULE:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DPM:
        case PPM:
          VarDef();
          break;
        case ALIAS:
          Alias();
          break;
        case IMPORT:
          Import();
          break;
        case INCLUDE:
          Include();
          break;
        case RULE:
          RuleDef();
          break;
        case RULESET:
          RulesetDef();
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GUIDELINE:
        GuidelineDef();
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      jj_consume_token(0);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void VarDef() throws ParseException {
 /*@bgen(jjtree) VarDef */
 ASTVarDef jjtn000 = new ASTVarDef(JJTVARDEF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm,typ;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DPM:
        jj_consume_token(DPM);
        typ = VarType();
                        jjtn000.data.put("ProductType",typ);jjtn000.data.put("Type","DPM");jjtn000.data.put("varType","DPM");
        nm = Name();
                                                                                                                                         jjtn000.data.put("Name",nm);
        EOS();
        break;
      case PPM:
        jj_consume_token(PPM);
        typ = PpmVarType();
                             jjtn000.data.put("Type",typ);jjtn000.data.put("varType","PPM");
        nm = Name();
                                                                                                        jjtn000.data.put("Name",nm);
        EOS();
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String VarType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
      jj_consume_token(BOOLEAN);
                    {if (true) return new String("1");}
      break;
    case DATE:
      jj_consume_token(DATE);
                    {if (true) return new String("2");}
      break;
    case MONEY:
      jj_consume_token(MONEY);
                    {if (true) return new String("3");}
      break;
    case NUMERIC:
      jj_consume_token(NUMERIC);
                    {if (true) return new String("4");}
      break;
    case PERCENTAGE:
      jj_consume_token(PERCENTAGE);
                    {if (true) return new String("5");}
      break;
    case TEXT:
      jj_consume_token(TEXT);
                    {if (true) return new String("6");}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String PpmVarType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case APPLICATION:
      jj_consume_token(APPLICATION);
                          {if (true) return new String("APP");}
      break;
    case CREDIT:
      jj_consume_token(CREDIT);
                          {if (true) return new String("CRD");}
      break;
    case PRODUCT:
      jj_consume_token(PRODUCT);
                          {if (true) return new String("PRD");}
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void Alias() throws ParseException {
 /*@bgen(jjtree) Alias */
 ASTAlias jjtn000 = new ASTAlias(JJTALIAS);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      jj_consume_token(ALIAS);
      jj_consume_token(LPAREN);
      AliasType();
      jj_consume_token(COMMA);
      nm = Name();
                                             jjtn000.data.put("Name",nm);
      jj_consume_token(COMMA);
      AliasOf();
      jj_consume_token(RPAREN);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void AliasType() throws ParseException {
 /*@bgen(jjtree) AliasType */
  ASTAliasType jjtn000 = new ASTAliasType(JJTALIASTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RULE:
        t = jj_consume_token(RULE);
                    jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.data.put("value",token.image);
        break;
      case RULESET:
        t = jj_consume_token(RULESET);
                    jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.data.put("value",token.image);
        break;
      case DPM:
        t = jj_consume_token(DPM);
                    jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.data.put("value",token.image);
        break;
      case PPM:
        t = jj_consume_token(PPM);
                    jjtree.closeNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.data.put("value",token.image);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void AliasOf() throws ParseException {
 /*@bgen(jjtree) AliasOf */
  ASTAliasOf jjtn000 = new ASTAliasOf(JJTALIASOF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      StringLiteral();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void EOS() throws ParseException {
    jj_consume_token(SEMICOLON);
  }

  final public void Import() throws ParseException {
 /*@bgen(jjtree) Import */
 ASTImport jjtn000 = new ASTImport(JJTIMPORT);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String it,fn;
    try {
      jj_consume_token(IMPORT);
      jj_consume_token(LPAREN);
      it = ImportType();
                                     jjtn000.data.put("importType",it);
      jj_consume_token(COMMA);
      fn = Filename();
                                                                                             jjtn000.data.put("filename",fn);
      jj_consume_token(RPAREN);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String Filename() throws ParseException {
    jj_consume_token(FILENAME_LITERAL);
                       {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

  final public String ImportType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DPM:
      jj_consume_token(DPM);
      break;
    case PPM:
      jj_consume_token(PPM);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

  final public void Include() throws ParseException {
 /*@bgen(jjtree) Include */
 ASTInclude jjtn000 = new ASTInclude(JJTINCLUDE);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String fn;
    try {
      jj_consume_token(INCLUDE);
      fn = ParenFilenameLiteral();
                                      jjtn000.data.put("filename",fn);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String ParenFilenameLiteral() throws ParseException {
 String fn;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      jj_consume_token(LPAREN);
      fn = Filename();
      jj_consume_token(RPAREN);
      break;
    case FILENAME_LITERAL:
      fn = Filename();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                           {if (true) return fn;}
    throw new Error("Missing return statement in function");
  }

  final public String ParenStringLiteral() throws ParseException {
 String str;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      jj_consume_token(LPAREN);
      str = StringLiteral();
      jj_consume_token(RPAREN);
      break;
    case STRING_LITERAL:
      str = StringLiteral();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                       {if (true) return str;}
    throw new Error("Missing return statement in function");
  }

  final public void GuidelineDef() throws ParseException {
 /*@bgen(jjtree) GuidelineDef */
 ASTGuidelineDef jjtn000 = new ASTGuidelineDef(JJTGUIDELINEDEF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      jj_consume_token(GUIDELINE);
      jj_consume_token(LPAREN);
      nm = ParenStringLiteral();
      jj_consume_token(RPAREN);
                                                            jjtn000.data.put("Name",nm);jjtn000.data.put("GuidelineID","1");jjtn000.data.put("Version","1");jjtn000.data.put("StartDate","");
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RULESET:
          if (jj_2_1(4)) {
            RulesetDef();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case RULESET:
              RulesetRef();
              break;
            default:
              jj_la1[10] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
          break;
        case RULE:
          if (jj_2_2(5)) {
            RuleRef();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case RULE:
              RuleDef();
              break;
            default:
              jj_la1[11] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RULESET:
        case RULE:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(END);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String StringLiteral() throws ParseException {
    jj_consume_token(STRING_LITERAL);
                      {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

  final public String Name() throws ParseException {
    jj_consume_token(IDENTIFIER);
                  {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

  final public void RulesetDef() throws ParseException {
 /*@bgen(jjtree) RulesetDef */
 ASTRulesetDef jjtn000 = new ASTRulesetDef(JJTRULESETDEF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm, et;
    try {
      jj_consume_token(RULESET);
      nm = Name();
                      jjtn000.data.put("Name",nm);jjtn000.data.put("Id","99999");jjtn000.data.put("Type","0");
      jj_consume_token(LPAREN);
      et = ExecuteType();
                                                                                                                                            jjtn000.data.put("ExecuteType",et);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        jj_consume_token(PL);
        break;
      default:
        jj_la1[14] = jj_gen;
        ;
      }
      jj_consume_token(RPAREN);
      label_3:
      while (true) {
        if (jj_2_3(5)) {
          RuleDef();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case RULE:
            RuleRef();
            break;
          default:
            jj_la1[15] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RULE:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_3;
        }
      }
      jj_consume_token(END);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String ExecuteType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
      jj_consume_token(TRUE);
                  {if (true) return new String("1");}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                  {if (true) return new String("2");}
      break;
    case CONTINUE:
      jj_consume_token(CONTINUE);
                  {if (true) return new String("3");}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void RulesetRef() throws ParseException {
 /*@bgen(jjtree) RulesetRef */
 ASTRulesetRef jjtn000 = new ASTRulesetRef(JJTRULESETREF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      jj_consume_token(RULESET);
      nm = Name();
                      jjtn000.data.put("Name",nm);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void RuleDef() throws ParseException {
 /*@bgen(jjtree) RuleDef */
 ASTRuleDef jjtn000 = new ASTRuleDef(JJTRULEDEF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      jj_consume_token(RULE);
      nm = Name();
                   jjtn000.data.put("Name",nm);jjtn000.data.put("Id","99999");
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      IfThenElse();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void RuleRef() throws ParseException {
 /*@bgen(jjtree) RuleRef */
 ASTRuleRef jjtn000 = new ASTRuleRef(JJTRULEREF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      jj_consume_token(RULE);
      nm = Name();
                   jjtn000.data.put("Name",nm);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void IfThenElse() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    Condition();
    jj_consume_token(RPAREN);
    jj_consume_token(THEN);
    IfActions();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      ElseActions();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(END);
  }

// COMPARISON EXPRESSIONS

/*
Condition  --> CompTerm ( AND1 CompTerm | AND2 CompTerm | OR1 CompTerm | OR2 CompTerm )*
*/
  final public void Condition() throws ParseException {
 /*@bgen(jjtree) Condition */
  ASTCondition jjtn000 = new ASTCondition(JJTCONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Expression();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
Expression  --> CompTerm ( AND1 CompTerm | AND2 CompTerm | OR1 CompTerm | OR2 CompTerm )*
*/
  final public void Expression() throws ParseException {
 /*@bgen(jjtree) Expression */
  ASTExpression jjtn000 = new ASTExpression(JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Compute();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
Compute  --> CompTerm ( AND1 CompTerm | AND2 CompTerm | OR1 CompTerm | OR2 CompTerm )*
*/
  final public void Compute() throws ParseException {
 /*@bgen(jjtree) #LogicalCompute(> 1) */
  ASTLogicalCompute jjtn000 = new ASTLogicalCompute(JJTLOGICALCOMPUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      CompTerm();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND1:
        case AND2:
        case OR1:
        case OR2:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_4;
        }
        LogicalOperator();
        CompTerm();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
    }
    }
  }

  final public void LogicalOperator() throws ParseException {
 /*@bgen(jjtree) LogicalOperator */
  ASTLogicalOperator jjtn000 = new ASTLogicalOperator(JJTLOGICALOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND1:
        t = jj_consume_token(AND1);
        break;
      case AND2:
        t = jj_consume_token(AND2);
        break;
      case OR1:
        t = jj_consume_token(OR1);
        break;
      case OR2:
        t = jj_consume_token(OR2);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
CompTerm  --> Primary ( LT Primary 
            | GT Primary
            | NEQ1 Primary
            | NEQ2 Primary
            | EQU Primary
            | LEQ Primary
            | GEQ Primary)*

*/
  final public void CompTerm() throws ParseException {
 /*@bgen(jjtree) #EqualityCompute(> 1) */
  ASTEqualityCompute jjtn000 = new ASTEqualityCompute(JJTEQUALITYCOMPUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Operand();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EQU:
        case NEQ1:
        case NEQ2:
        case LT:
        case GT:
        case LEQ:
        case GEQ:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_5;
        }
        EqualityOperator();
        Operand();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
    }
    }
  }

  final public void EqualityOperator() throws ParseException {
 /*@bgen(jjtree) EqualityOperator */
  ASTEqualityOperator jjtn000 = new ASTEqualityOperator(JJTEQUALITYOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
        t = jj_consume_token(LT);
        break;
      case GT:
        t = jj_consume_token(GT);
        break;
      case NEQ1:
        t = jj_consume_token(NEQ1);
        break;
      case NEQ2:
        t = jj_consume_token(NEQ2);
        break;
      case EQU:
        t = jj_consume_token(EQU);
        break;
      case LEQ:
        t = jj_consume_token(LEQ);
        break;
      case GEQ:
        t = jj_consume_token(GEQ);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
Operand   --> NUMERIC_CONSTANT
        | STRING_LITERAL
        | VarRef
        | LPAREN Compute RPAREN

*/
  final public void Operand() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERIC_CONSTANT:
    case STRING_LITERAL:
      Constant();
      break;
    case IDENTIFIER:
      VarRef();
      break;
    case LPAREN:
      Brace();
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Brace() throws ParseException {
 /*@bgen(jjtree) Brace */
  ASTBrace jjtn000 = new ASTBrace(JJTBRACE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      Compute();
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Constant() throws ParseException {
 /*@bgen(jjtree) Constant */
  ASTConstant jjtn000 = new ASTConstant(JJTCONSTANT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMERIC_CONSTANT:
        t = jj_consume_token(NUMERIC_CONSTANT);
        break;
      case STRING_LITERAL:
        t = jj_consume_token(STRING_LITERAL);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                           jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
                           jjtn000.data.put("value",t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

// MATH EXPRESSIONS

/*
MathExpression  --> MathTerm ( PLUS MathTerm | MINUS MathTerm )*
*/
  final public void MathExpression() throws ParseException {
 /*@bgen(jjtree) MathExpression */
  ASTMathExpression jjtn000 = new ASTMathExpression(JJTMATHEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MCompute();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
MCompute  --> MathTerm ( PLUS MathTerm | MINUS MathTerm )*
*/
  final public void MCompute() throws ParseException {
 /*@bgen(jjtree) #MathCompute(> 1) */
  ASTMathCompute jjtn000 = new ASTMathCompute(JJTMATHCOMPUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MathCompute();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
        case MINUS:
          ;
          break;
        default:
          jj_la1[25] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          PlusOperator();
          MathCompute();
          break;
        case MINUS:
          MinusOperator();
          MathCompute();
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
    }
    }
  }

/*
PlusOperator - This is here so that the tree builds correctly and the 
                operator can be retrieved.
*/
  final public void PlusOperator() throws ParseException {
 /*@bgen(jjtree) PlusOperator */
  ASTPlusOperator jjtn000 = new ASTPlusOperator(JJTPLUSOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(PLUS);
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
            jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
MinusOperator - This is here so that the tree builds correctly and the 
                operator can be retrieved.
*/
  final public void MinusOperator() throws ParseException {
 /*@bgen(jjtree) MinusOperator */
  ASTMinusOperator jjtn000 = new ASTMinusOperator(JJTMINUSOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(MINUS);
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
             jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
MathCompute    --> MTerm ( MULT MTerm | DIV MTerm )*
*/
  final public void MathCompute() throws ParseException {
 /*@bgen(jjtree) #MathCompute(> 1) */
  ASTMathCompute jjtn000 = new ASTMathCompute(JJTMATHCOMPUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MultTerm();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULT:
        case DIV:
          ;
          break;
        default:
          jj_la1[27] = jj_gen;
          break label_7;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULT:
          MultOperator();
          MultTerm();
          break;
        case DIV:
          DivOperator();
          MultTerm();
          break;
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
    }
    }
  }

/*
MultOperator - This is here so that the tree builds correctly and the 
                operator can be retrieved.
*/
  final public void MultOperator() throws ParseException {
 /*@bgen(jjtree) MultOperator */
  ASTMultOperator jjtn000 = new ASTMultOperator(JJTMULTOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(MULT);
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
            jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
DivOperator - This is here so that the tree builds correctly and the 
                operator can be retrieved.
*/
  final public void DivOperator() throws ParseException {
 /*@bgen(jjtree) DivOperator */
  ASTDivOperator jjtn000 = new ASTDivOperator(JJTDIVOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(DIV);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
           jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
MultTerm     --> MathOperand ( RAISETO MathOperand )*
*/
  final public void MultTerm() throws ParseException {
 /*@bgen(jjtree) #MathCompute(> 1) */
  ASTMathCompute jjtn000 = new ASTMathCompute(JJTMATHCOMPUTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      MathOperand();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RAISETO:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_8;
        }
        RaiseToOperator();
        MathOperand();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, jjtree.nodeArity() > 1);
    }
    }
  }

/*
RaiseToOperator - This is here so that the tree builds correctly and the 
                operator can be retrieved.
*/
  final public void RaiseToOperator() throws ParseException {
 /*@bgen(jjtree) RaiseToOperator */
  ASTRaiseToOperator jjtn000 = new ASTRaiseToOperator(JJTRAISETOOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(RAISETO);
                jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
               jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/*
MathOperand   --> NUMERIC_CONSTANT
          | LPAREN MathExpression RPAREN
          | MINUS MathOperand
          

*/
  final public void MathOperand() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERIC_CONSTANT:
      MathConstant();
      break;
    case IDENTIFIER:
      VarRef();
      break;
    case LPAREN:
      MathBrace();
      break;
    case MINUS:
      jj_consume_token(MINUS);
      MathOperand();
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void MathBrace() throws ParseException {
 /*@bgen(jjtree) Brace */
  ASTBrace jjtn000 = new ASTBrace(JJTBRACE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      MCompute();
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void MathConstant() throws ParseException {
 /*@bgen(jjtree) MathConstant */
  ASTMathConstant jjtn000 = new ASTMathConstant(JJTMATHCONSTANT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(NUMERIC_CONSTANT);
                         jjtree.closeNodeScope(jjtn000, true);
                         jjtc000 = false;
                         jjtn000.data.put("value", t.image );
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void IfActions() throws ParseException {
 /*@bgen(jjtree) IfActions */
  ASTIfActions jjtn000 = new ASTIfActions(JJTIFACTIONS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MESSAGE:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_9;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          Assign();
          break;
        case MESSAGE:
          Message();
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void ElseActions() throws ParseException {
 /*@bgen(jjtree) ElseActions */
  ASTElseActions jjtn000 = new ASTElseActions(JJTELSEACTIONS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MESSAGE:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[33] = jj_gen;
          break label_10;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          Assign();
          break;
        case MESSAGE:
          Message();
          break;
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Assign() throws ParseException {
 /*@bgen(jjtree) Assign */
  ASTAssign jjtn000 = new ASTAssign(JJTASSIGN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      AssignTo();
      jj_consume_token(ASSIGN);
      AssignValue();
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void AssignTo() throws ParseException {
 /*@bgen(jjtree) AssignTo */
  ASTAssignTo jjtn000 = new ASTAssignTo(JJTASSIGNTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      VarRef();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void AssignValue() throws ParseException {
 /*@bgen(jjtree) AssignValue */
  ASTAssignValue jjtn000 = new ASTAssignValue(JJTASSIGNVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_4(2)) {
        MathExpression();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NUMERIC_CONSTANT:
        case STRING_LITERAL:
          ConstantExpression();
          break;
        default:
          jj_la1[35] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void ConstantExpression() throws ParseException {
 /*@bgen(jjtree) Expression */
  ASTExpression jjtn000 = new ASTExpression(JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Constant();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Message() throws ParseException {
 /*@bgen(jjtree) Message */
  ASTMessage jjtn000 = new ASTMessage(JJTMESSAGE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MESSAGE);
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MSG_EXC:
        Exptn();
        jj_consume_token(COMMA);
        ExptnType();
        break;
      case MSG_FINDINGS:
      case MSG_OBSERVATION:
      case MSG_CREDIT:
        MessageType();
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COMMA);
      StringLiteral();
      jj_consume_token(RPAREN);
      EOS();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Exptn() throws ParseException {
 /*@bgen(jjtree) Exptn */
  ASTExptn jjtn000 = new ASTExptn(JJTEXPTN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MSG_EXC);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void ExptnType() throws ParseException {
 /*@bgen(jjtree) ExptnType */
  ASTExptnType jjtn000 = new ASTExptnType(JJTEXPTNTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MSG_EXC_ASSETS:
        t = jj_consume_token(MSG_EXC_ASSETS);
        break;
      case MSG_EXC:
        t = jj_consume_token(MSG_EXC);
        break;
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                         jjtree.closeNodeScope(jjtn000, true);
                                         jjtc000 = false;
                                         jjtn000.data.put("value", t.image);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void MessageType() throws ParseException {
 /*@bgen(jjtree) MessageType */
  ASTMessageType jjtn000 = new ASTMessageType(JJTMESSAGETYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MSG_FINDINGS:
        t = jj_consume_token(MSG_FINDINGS);
        break;
      case MSG_OBSERVATION:
        t = jj_consume_token(MSG_OBSERVATION);
        break;
      case MSG_CREDIT:
        t = jj_consume_token(MSG_CREDIT);
        break;
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                jjtree.closeNodeScope(jjtn000, true);
                                                                jjtc000 = false;
                                                                jjtn000.data.put("value", t.image);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void VarRef() throws ParseException {
 /*@bgen(jjtree) VarRef */
 ASTVarRef jjtn000 = new ASTVarRef(JJTVARREF);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String nm;
    try {
      nm = Name();
             jjtree.closeNodeScope(jjtn000, true);
             jjtc000 = false;
            jjtn000.data.put("Name",nm);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void VarCast() throws ParseException {
 /*@bgen(jjtree) VarCast */
  ASTVarCast jjtn000 = new ASTVarCast(JJTVARCAST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      VariableType();
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void VariableType() throws ParseException {
 /*@bgen(jjtree) VariableType */
  ASTVariableType jjtn000 = new ASTVariableType(JJTVARIABLETYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DPM:
        jj_consume_token(DPM);
        break;
      case DSM:
        jj_consume_token(DSM);
        break;
      case PPM:
        jj_consume_token(PPM);
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void AndOperator() throws ParseException {
 /*@bgen(jjtree) AndOperator */
  ASTAndOperator jjtn000 = new ASTAndOperator(JJTANDOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND1:
        jj_consume_token(AND1);
        break;
      case AND2:
        jj_consume_token(AND2);
        break;
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void OrOperator() throws ParseException {
 /*@bgen(jjtree) OrOperator */
  ASTOrOperator jjtn000 = new ASTOrOperator(JJTOROPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR1:
        jj_consume_token(OR1);
        break;
      case OR2:
        jj_consume_token(OR2);
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_3R_21() {
    if (jj_scan_token(CONTINUE)) return true;
    return false;
  }

  final private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_3R_32()) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  final private boolean jj_3R_43() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_42() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  final private boolean jj_3R_36() {
    if (jj_3R_43()) return true;
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_3R_42()) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3R_11() {
    if (jj_scan_token(RULESET)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_34() {
    if (jj_3R_41()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    if (jj_3R_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_23()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_15() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    if (jj_3R_18()) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_38()) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    if (jj_scan_token(RAISETO)) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_3R_40()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3R_24() {
    if (jj_3R_28()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_29()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    if (jj_scan_token(DIV)) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    if (jj_scan_token(IF)) return true;
    return false;
  }

  final private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_3R_33()) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    if (jj_3R_39()) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    if (jj_scan_token(MULT)) return true;
    return false;
  }

  final private boolean jj_3R_12() {
    if (jj_scan_token(RULE)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(55)) return true;
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_3R_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_13() {
    if (jj_scan_token(RULE)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_scan_token(NUMERIC_CONSTANT)) return true;
    return false;
  }

  public GdlParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[42];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_0();
      jj_la1_1();
      jj_la1_2();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x3001780,0x3001780,0x800000,0x1400,0xfc000,0x700000,0x3001400,0x1400,0x0,0x0,0x1000000,0x2000000,0x3000000,0x3000000,0x0,0x2000000,0x2000000,0x80000000,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4000000,0x4000000,0x4000000,0x4000000,0x0,0x0,0x0,0x0,0x1c00,0x0,0x0,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30000,0x28000,0x0,0x0,0x0,0x0,0x1000000,0x0,0x0,0x3,0x0,0x0,0x0,0x0,0x0,0x28080,0x8080,0xc0000000,0xc0000000,0x0,0x0,0x0,0x80020080,0x0,0x0,0x0,0x0,0x8080,0x74,0xc,0x70,0x0,0x0,0x0,};
   }
   private static void jj_la1_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3c00,0x3c00,0x3f8,0x3f8,0x4000,0x0,0x0,0x0,0x3,0x3,0x4,0x4000,0x4000,0x4000,0x4000,0x4000,0x0,0x0,0x0,0x0,0x0,0xc00,0x3000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[4];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public GdlParser(java.io.InputStream stream) {
     this(stream, null);
  }
  public GdlParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GdlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public GdlParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GdlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public GdlParser(GdlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(GdlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[81];
    for (int i = 0; i < 81; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 42; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 81; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
