/* Generated By:JJTree&JavaCC: Do not edit this line. GdlParserConstants.java */
package runtime.parser;

public interface GdlParserConstants {

  int EOF = 0;
  int ALIAS = 5;
  int INCLUDE = 6;
  int IMPORT = 7;
  int DPM = 8;
  int DSM = 9;
  int PPM = 10;
  int DECISION = 11;
  int BOOLEAN = 12;
  int DATE = 13;
  int MONEY = 14;
  int NUMERIC = 15;
  int PERCENTAGE = 16;
  int TEXT = 17;
  int APPLICATION = 18;
  int CREDIT = 19;
  int PRODUCT = 20;
  int GUIDELINE = 21;
  int RULESET = 22;
  int RULE = 23;
  int MESSAGE = 24;
  int IF = 25;
  int THEN = 26;
  int ELSE = 27;
  int END = 28;
  int TRUE = 29;
  int FALSE = 30;
  int CONTINUE = 31;
  int MSG_EXC = 32;
  int MSG_EXC_ASSETS = 33;
  int MSG_FINDINGS = 34;
  int MSG_OBSERVATION = 35;
  int MSG_CREDIT = 36;
  int NUMERIC_CONSTANT = 37;
  int INTEGER_LITERAL = 38;
  int DECIMAL_LITERAL = 39;
  int HEX_LITERAL = 40;
  int OCTAL_LITERAL = 41;
  int FLOATING_POINT_LITERAL = 42;
  int EXPONENT = 43;
  int CHARACTER_LITERAL = 44;
  int STRING_LITERAL = 45;
  int FILENAME_LITERAL = 46;
  int LPAREN = 47;
  int RPAREN = 48;
  int LBRACE = 49;
  int RBRACE = 50;
  int LBRACKET = 51;
  int RBRACKET = 52;
  int SEMICOLON = 53;
  int COMMA = 54;
  int DOT = 55;
  int PL = 56;
  int ASSIGN = 57;
  int QUOTE = 58;
  int DQUOTE = 59;
  int PLUS = 60;
  int MINUS = 61;
  int MULT = 62;
  int DIV = 63;
  int RAISETO = 64;
  int EQU = 65;
  int NEQ1 = 66;
  int NEQ2 = 67;
  int LT = 68;
  int GT = 69;
  int LEQ = 70;
  int GEQ = 71;
  int AND1 = 72;
  int AND2 = 73;
  int OR1 = 74;
  int OR2 = 75;
  int IDENTIFIER = 76;
  int LETTER = 77;
  int DIGIT = 78;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"alias\"",
    "\"include\"",
    "\"import\"",
    "\"dpm\"",
    "\"dsm\"",
    "\"ppm\"",
    "\"decision\"",
    "\"boolean\"",
    "\"date\"",
    "\"money\"",
    "\"numeric\"",
    "\"percentage\"",
    "\"text\"",
    "\"app\"",
    "\"crd\"",
    "\"prd\"",
    "\"guideline\"",
    "\"ruleset\"",
    "\"rule\"",
    "\"message\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"end\"",
    "<TRUE>",
    "<FALSE>",
    "\"continue\"",
    "\"exception\"",
    "\"assets\"",
    "\"findings\"",
    "\"observation\"",
    "\"credit\"",
    "<NUMERIC_CONSTANT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<FILENAME_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"PL\"",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"and\"",
    "\"||\"",
    "\"or\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
